# Generated by Django 2.1 on 2018-08-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeblog', '0003_auto_20180823_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datePosted',
            field=models.DateTimeField(verbose_name='Date published'),
        ),
    ]
