# Generated by Django 2.1 on 2018-08-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeblog', '0004_auto_20180823_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datePosted',
            field=models.DateField(verbose_name='Date published'),
        ),
    ]
