# Generated by Django 2.1 on 2018-08-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeblog', '0005_auto_20180823_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postedBy',
            field=models.CharField(default='xyz', max_length=100),
            preserve_default=False,
        ),
    ]
