# Generated by Django 2.1 on 2018-08-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeblog', '0006_post_postedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='calorie',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
