# Generated by Django 2.1 on 2018-08-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_falseuser_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='falseuser',
            name='calorieDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='falseuser',
            name='calorieGoal',
            field=models.IntegerField(default='-1'),
        ),
    ]
