# Generated by Django 2.1 on 2018-08-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180824_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falseuser',
            name='age',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='falseuser',
            name='calorieGoal',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='falseuser',
            name='height',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='falseuser',
            name='weight',
            field=models.FloatField(default=-1),
        ),
    ]
